plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'org.jpos.jposapp' version '0.0.16'
}

group = 'org.jpos.template'
version = '3.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = uri('https://jpos.org/maven') }
    mavenLocal()
}

ext.awsSdkVersion = '2.29.51'

dependencies {
    implementation 'org.jpos:jpos:3.0.1-SNAPSHOT'
    implementation "software.amazon.awssdk:paymentcryptographydata:${awsSdkVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

jpos {
    distDir.set('src/dist')
}

tasks.named('test') {
    useJUnitPlatform {
        if (!project.hasProperty('integrationTests')) {
            excludeTags 'integration'
        }
    }
    systemProperty 'q2.port', (project.findProperty('q2Port') ?: '8080')
}
