apiVersion: v1
kind: Secret
metadata:
  name: apc-config
type: Opaque
stringData:
  # Keep in same region as EKS/PaymentCryptoStack
  APC_REGION: ap-southeast-1
  # From PaymentCryptoStack output PaymentCryptographyPinKeyAlias
  APC_PIN_KEY_ALIAS: alias/cde-demo-pin
  # Optional; defaults to APC_PIN_KEY_ALIAS in code path
  APC_MAC_KEY_ALIAS: alias/cde-demo-pin
